// <auto-generated />
using System;
using ChronoCorp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChronoCorp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250507133521_MajCeduleQuart")]
    partial class MajCeduleQuart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ChronoCorp.Model.CedulePointage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("HeureDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HeureFin")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IdEmployee")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("IdEmployee");

                    b.ToTable("CedulePointage");
                });

            modelBuilder.Entity("ChronoCorp.Model.CeduleQuart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("HeureDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("HeureDepart")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("HeureEntree")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("HeureFin")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IdCreateur")
                        .HasColumnType("bigint");

                    b.Property<long>("IdEmployee")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsPausePayee")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("TypeQuart")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdCreateur");

                    b.HasIndex("IdEmployee");

                    b.HasIndex("TypeQuart");

                    b.ToTable("Cedule_Quart");
                });

            modelBuilder.Entity("ChronoCorp.Model.DemandeConge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Commentaire")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("EstApprouve")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("IdDestinataire")
                        .HasColumnType("bigint");

                    b.Property<long>("IdEmetteur")
                        .HasColumnType("bigint");

                    b.Property<string>("Reponse")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("TempsModif")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("TempsSoumission")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TypeQuart")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdDestinataire");

                    b.HasIndex("IdEmetteur");

                    b.HasIndex("TypeQuart");

                    b.ToTable("Demande_Conge");
                });

            modelBuilder.Entity("ChronoCorp.Model.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdresseLigne1")
                        .HasColumnType("longtext");

                    b.Property<string>("AdresseLigne2")
                        .HasColumnType("longtext");

                    b.Property<float?>("ArgentGagneTotal")
                        .HasColumnType("float");

                    b.Property<string>("CodePostal")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactUrgenceNom")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactUrgenceTel")
                        .HasColumnType("longtext");

                    b.Property<string>("Courriel")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Departement")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("EstActif")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("IdSuperieur")
                        .HasColumnType("bigint");

                    b.Property<float?>("NbrHeureConge")
                        .HasColumnType("float");

                    b.Property<float?>("NbrHeureTotal")
                        .HasColumnType("float");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Salaire")
                        .HasColumnType("float");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ville")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdSuperieur");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("ChronoCorp.Model.EmployeeCredentials", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<string>("Mdp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Employee_Credentials");
                });

            modelBuilder.Entity("ChronoCorp.Model.FichePaie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DatePaie")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("IdEmployee")
                        .HasColumnType("bigint");

                    b.Property<float>("Montant")
                        .HasColumnType("float");

                    b.Property<float>("NbrHeure")
                        .HasColumnType("float");

                    b.Property<float>("VacanceCumul")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdEmployee");

                    b.ToTable("Fiche_Paie");
                });

            modelBuilder.Entity("ChronoCorp.Model.Messagerie", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("IdDestinataire")
                        .HasColumnType("bigint");

                    b.Property<long>("IdEmetteur")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Temps")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("TypeMessage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("IdDestinataire");

                    b.HasIndex("IdEmetteur");

                    b.ToTable("Messagerie");
                });

            modelBuilder.Entity("ChronoCorp.Model.TypeQuart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("EstConge")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("TauxMajoration")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Type_Quart");
                });

            modelBuilder.Entity("ChronoCorp.Model.CedulePointage", b =>
                {
                    b.HasOne("ChronoCorp.Model.Employee", "Employee")
                        .WithMany("CedulePointages")
                        .HasForeignKey("IdEmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ChronoCorp.Model.CeduleQuart", b =>
                {
                    b.HasOne("ChronoCorp.Model.Employee", "Gestionnaire")
                        .WithMany("CeduleQuartsGest")
                        .HasForeignKey("IdCreateur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChronoCorp.Model.Employee", "Employee")
                        .WithMany("CeduleQuartsEmp")
                        .HasForeignKey("IdEmployee")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChronoCorp.Model.TypeQuart", "TypeDuQuart")
                        .WithMany("CeduleQuarts")
                        .HasForeignKey("TypeQuart")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Gestionnaire");

                    b.Navigation("TypeDuQuart");
                });

            modelBuilder.Entity("ChronoCorp.Model.DemandeConge", b =>
                {
                    b.HasOne("ChronoCorp.Model.Employee", "Gestionnaire")
                        .WithMany("ApprobationConges")
                        .HasForeignKey("IdDestinataire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChronoCorp.Model.Employee", "Employee")
                        .WithMany("DemandeConges")
                        .HasForeignKey("IdEmetteur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChronoCorp.Model.TypeQuart", "TypeQuarts")
                        .WithMany("DemandesConges")
                        .HasForeignKey("TypeQuart")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Gestionnaire");

                    b.Navigation("TypeQuarts");
                });

            modelBuilder.Entity("ChronoCorp.Model.Employee", b =>
                {
                    b.HasOne("ChronoCorp.Model.Employee", "Gestionnaire")
                        .WithMany()
                        .HasForeignKey("IdSuperieur");

                    b.Navigation("Gestionnaire");
                });

            modelBuilder.Entity("ChronoCorp.Model.EmployeeCredentials", b =>
                {
                    b.HasOne("ChronoCorp.Model.Employee", "Employee")
                        .WithOne("employeeCredentials")
                        .HasForeignKey("ChronoCorp.Model.EmployeeCredentials", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ChronoCorp.Model.FichePaie", b =>
                {
                    b.HasOne("ChronoCorp.Model.Employee", "Employee")
                        .WithMany("FichePaies")
                        .HasForeignKey("IdEmployee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ChronoCorp.Model.Messagerie", b =>
                {
                    b.HasOne("ChronoCorp.Model.Employee", "Employee2")
                        .WithMany("MessagerieReceiver")
                        .HasForeignKey("IdDestinataire")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChronoCorp.Model.Employee", "Employee1")
                        .WithMany("MessagerieSender")
                        .HasForeignKey("IdEmetteur")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee1");

                    b.Navigation("Employee2");
                });

            modelBuilder.Entity("ChronoCorp.Model.Employee", b =>
                {
                    b.Navigation("ApprobationConges");

                    b.Navigation("CedulePointages");

                    b.Navigation("CeduleQuartsEmp");

                    b.Navigation("CeduleQuartsGest");

                    b.Navigation("DemandeConges");

                    b.Navigation("FichePaies");

                    b.Navigation("MessagerieReceiver");

                    b.Navigation("MessagerieSender");

                    b.Navigation("employeeCredentials")
                        .IsRequired();
                });

            modelBuilder.Entity("ChronoCorp.Model.TypeQuart", b =>
                {
                    b.Navigation("CeduleQuarts");

                    b.Navigation("DemandesConges");
                });
#pragma warning restore 612, 618
        }
    }
}
