// <auto-generated />
using System;
using ChronoCorp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChronoCorp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250507005637_AjoutModel")]
    partial class AjoutModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ChronoCorp.Model.Employee", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AdresseLigne1")
                        .HasColumnType("longtext");

                    b.Property<string>("AdresseLigne2")
                        .HasColumnType("longtext");

                    b.Property<float?>("ArgentGagneTotal")
                        .HasColumnType("float");

                    b.Property<string>("CodePostal")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactUrgenceNom")
                        .HasColumnType("longtext");

                    b.Property<string>("ContactUrgenceTel")
                        .HasColumnType("longtext");

                    b.Property<string>("Courriel")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateEmbauche")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Departement")
                        .HasColumnType("longtext");

                    b.Property<bool>("EstActif")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("IdSuperieur")
                        .HasColumnType("int");

                    b.Property<float?>("NbrHeureConge")
                        .HasColumnType("float");

                    b.Property<float?>("NbrHeureTotal")
                        .HasColumnType("float");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Poste")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("Salaire")
                        .HasColumnType("float");

                    b.Property<string>("Telephone")
                        .HasColumnType("longtext");

                    b.Property<string>("Ville")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
